apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-api-user-app
  name: udagram-api-user-app-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/udagram-api-user-app-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: udagram-api-user-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
